[tool.poetry]
name = "quiz"
version = "0.1.0"
description = "a quiz app that i was forced to make"
authors = ["ezntek <eason@ezntek.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
